title: "Bishal Koirala"
description: "QA Engineer | Manual & Automation Testing | 7+ Months Experience"
author:
  name: "Bishal Koirala"
  email: "bishal.koirala212@gmail.com"

linkedin_username: bishalkoirala-qa
github_username: Bee-salk21

show_excerpts: false
